### ISSUE TITLE
quickstart failing in existing vpc due to missing /etc/kubernetes/pki/ca.crt file

### ISSUE THREAD

**Issue by krisdock** [heptio/aws-quickstart#129] opened 2018-01-12 17:33 UTC
I am attempting to deploy the Heptio-Kubernetes stack into an existing 
AWS VPC. We are currently trying to stand up a PoC in the N. California 
(us-west-1a) az/region; I started by changing the dropdown in the top 
right corner, and for subsequent attmepts used the following URL:

https://us-west-1.console.aws.amazon.com/cloudformation/home?region=us-west-1#/stacks/new?stackName=Heptio-Kubernetes&templateURL=https:%2F%2Fs3.amazonaws.com%2Fquickstart-reference%2Fheptio%2Flatest%2Ftemplates%2Fkubernetes-cluster.template

I've created two subnets in our VPC (10.10.0.0/16): 10.10.18.0/24 for 
the cluster, and 10.10.84.0/24 for the load balancer. I verified that 
the subnets are in the same AZ as the VPC.

I left all the input boxes under Advanced on the second page with their 
default values:

- S3 Bucket: "quickstart-reference" 
- S3 Key Prefix: "heptio/latest" 
- empty cluster association

I also configured 0.0.0.0/0 for both ingress locations, and provided my 
EC2 keypair. I've verified that my IAM is admin for our account, and 
I left the arn empty so that it used my account's permissions.

A few things to note:

- our VPCs/subnets/etc. are in the N. California AZ (us-west-1a, specifically)

- when the formation creation failed in the past it was during K8sMasterInstance instance creation and I got the following status reason:

```
Failed to receive 1 resource signal(s) within the specified duration
```

- when I disable rollback on failure and try again the reported status reason is: 

```
Received FAILURE signal with UniqueId i-0aa60d8fd8f279dfc
```

- when I ssh onto the node and poke around I find the following:

```
ubuntu@ip-10-10-19-149:~$ sudo systemctl status kubelet 
sudo: unable to resolve host ip-10-10-19-149 
● kubelet.service - kubelet: The Kubernetes Node Agent 
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled) 
Drop-In: /etc/systemd/system/kubelet.service.d 
└─10-kubeadm.conf, 20-cloud-provider.conf 
Active: activating (auto-restart) (Result: exit-code) since Fri 2018-01-12 17:13:03 UTC; 396ms ago 
Docs: http://kubernetes.io/docs/ 
Process: 9502 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE) 
Main PID: 9502 (code=exited, status=1/FAILURE) 

Jan 12 17:13:03 ip-10-10-19-149 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE 
Jan 12 17:13:03 ip-10-10-19-149 systemd[1]: kubelet.service: Unit entered failed state. 
Jan 12 17:13:03 ip-10-10-19-149 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

where the full logs indicate that there is a missing file (/etc/kubernetes/pki/ca.crt\):

```
ubuntu@ip-10-10-19-149:~$ sudo journalctl -f -u kubelet 
[ snip ] 
Jan 12 17:14:56 ip-10-10-19-149 kubelet[9727]: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory 
[ snip ]
```

Is there a known bug that would prevent CloudFormation from placing that file down?

Orthogonally: I got the "Deploy Kubernetes into a new VPC on AWS" to succeed at 
creating on my first try, if that helps narrow down issues related to granted 
permissions on my account (we've got a substantial AWS footprint, so I'm fairly 
confident it's not related to account limits).

Any thoughts?

--
Stephen

**Comment by chuckha** [comment] 2018-01-12 18:49
Hi Stephen, thanks for the detailed report!

`kubeadm init` is the thing that will create those pki files. There should be logs in CloudWatch that may have more detail about why `kubeadm` can't put those files there. Do you still have the CloudWatch logs kicking around?

**Comment by smcquay** [comment] 2018-01-12 19:50
I already tore it down, but it wasn't too bad to recreate.

From `/var/log/cfn-*` I am seeing references to:

```log
2018-01-12 19:38:38,643 P1712 [INFO]    HOSTNAME="$(hostname -f)"
2018-01-12 19:38:38,643 P1712 [INFO]    hostname -f
2018-01-12 19:38:38,643 P1712 [INFO]    hostname: Name or service not known
```

and 

```log
HOSTNAME="$(hostname -f)"
hostname -f
hostname: Name or service not known

2018-01-12 19:38:38,645 [ERROR] Error encountered during build of master-setup: Command 03-master-setup failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 03-master-setup failed
2018-01-12 19:38:38,658 [ERROR] -----------------------BUILD FAILED!------------------------
2018-01-12 19:38:38,658 [ERROR] Unhandled exception during build: Command 03-master-setup failed
Traceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command 03-master-setup failed
2018-01-12 19:38:39,221 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-west-1.amazonaws.com
2018-01-12 19:38:39,221 [DEBUG] Signaling resource K8sMasterInstance in stack Heptio-Kubernetes with unique ID i-0f9fe535b295c66af and status FAILURE
```

I've verified that `hostname -f` fails interactively as well. I'm asking around on our side to see if there's anything peculiar about our setup that would cause that to fail.

Anything else you'd like from this node?

**Comment by chuckha** [comment] 2018-01-12 19:57
Nothing else, thank you.

Checkout the DHCP options on your VPC.

See https://github.com/heptio/aws-quickstart/issues/118 for a similar failure.

**Comment by smcquay** [comment] 2018-01-12 20:34
That failure is identical (also failing above in the curl commands).

Checking to see if there's anything we can do.

**Comment by smcquay** [comment] 2018-01-16 18:20
I can't seem to get that curl command to succeed regardless of the machine I'm running it on (including all the machines that I just stood up in a fresh VPC). Perhaps that command is a red herring.

Would it be sufficient for the Stack to progress if I configure things such that `hostname -f` works?

**Comment by craigtracey** [comment] 2018-01-16 18:24
@smcquay the `curl`  command getting a 403 in https://github.com/heptio/aws-quickstart/issues/118 has nothing to do with stack failure.  That mechanism is used for installing development binaries on a development stack.

Though, `hostname -f` being functional is a requirement.

**Comment by smcquay** [comment] 2018-01-16 18:54
@craigtracey thanks for the response. I'll see what, if anything, we can do with our VPCs to make progress forward.

**Comment by chuckha** [comment] 2018-01-18 15:42
@smcquay if you're up for an experiment I'd be interested to see the output of `strace hostname -f`  on your system that cannot run `hostname -f` (you can use `strace -otrace hostname -f` to to write the output to a file called `trace`)

**Comment by smcquay** [comment] 2018-01-19 21:41
```
execve("/bin/hostname", ["hostname", "-f"], [/* 20 vars */]) = 0
brk(NULL)                               = 0x20c4000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24563, ...}) = 0
mmap(NULL, 24563, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7efdbf9e4000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnsl.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360?\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=93128, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efdbf9e3000
mmap(NULL, 2198104, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efdbf5ac000
mprotect(0x7efdbf5c2000, 2093056, PROT_NONE) = 0
mmap(0x7efdbf7c1000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7efdbf7c1000
mmap(0x7efdbf7c3000, 6744, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7efdbf7c3000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efdbf1e2000
mprotect(0x7efdbf3a2000, 2097152, PROT_NONE) = 0
mmap(0x7efdbf5a2000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7efdbf5a2000
mmap(0x7efdbf5a8000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7efdbf5a8000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efdbf9e2000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efdbf9e1000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efdbf9e0000
arch_prctl(ARCH_SET_FS, 0x7efdbf9e1700) = 0
mprotect(0x7efdbf5a2000, 16384, PROT_READ) = 0
mprotect(0x7efdbf7c1000, 4096, PROT_READ) = 0
mprotect(0x602000, 4096, PROT_READ)     = 0
mprotect(0x7efdbf9ea000, 4096, PROT_READ) = 0
munmap(0x7efdbf9e4000, 24563)           = 0
brk(NULL)                               = 0x20c4000
brk(0x20e5000)                          = 0x20e5000
uname({sysname="Linux", nodename="ip-10-10-84-118", ...}) = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
close(3)                                = 0
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=497, ...}) = 0
read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 4096) = 497
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=92, ...}) = 0
read(3, "# The \"order\" line is only used "..., 4096) = 92
read(3, "", 4096)                       = 0
close(3)                                = 0
getpid()                                = 23301
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=214, ...}) = 0
read(3, "# Dynamic resolv.conf(5) file fo"..., 4096) = 214
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24563, ...}) = 0
mmap(NULL, 24563, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7efdbf9e4000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260!\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=47600, ...}) = 0
mmap(NULL, 2168600, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efdbefd0000
mprotect(0x7efdbefdb000, 2093056, PROT_NONE) = 0
mmap(0x7efdbf1da000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa000) = 0x7efdbf1da000
mmap(0x7efdbf1dc000, 22296, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7efdbf1dc000
close(3)                                = 0
mprotect(0x7efdbf1da000, 4096, PROT_READ) = 0
munmap(0x7efdbf9e4000, 24563)           = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=221, ...}) = 0
read(3, "127.0.0.1 localhost\n\n# The follo"..., 4096) = 221
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24563, ...}) = 0
mmap(NULL, 24563, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7efdbf9e4000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\17\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=27000, ...}) = 0
mmap(NULL, 2121944, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efdbedc9000
mprotect(0x7efdbedce000, 2097152, PROT_NONE) = 0
mmap(0x7efdbefce000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7efdbefce000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P9\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=101200, ...}) = 0
mmap(NULL, 2206280, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7efdbebae000
mprotect(0x7efdbebc5000, 2097152, PROT_NONE) = 0
mmap(0x7efdbedc5000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7efdbedc5000
mmap(0x7efdbedc7000, 6728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7efdbedc7000
close(3)                                = 0
mprotect(0x7efdbedc5000, 4096, PROT_READ) = 0
mprotect(0x7efdbefce000, 4096, PROT_READ) = 0
munmap(0x7efdbf9e4000, 24563)           = 0
stat("/etc/resolv.conf", {st_mode=S_IFREG|0644, st_size=214, ...}) = 0
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=214, ...}) = 0
read(3, "# Dynamic resolv.conf(5) file fo"..., 4096) = 214
read(3, "", 4096)                       = 0
close(3)                                = 0
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, 16) = 0
gettimeofday({1516398059, 59067}, NULL) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendmmsg(3, {{{msg_name(0)=NULL, msg_iov(1)=[{"ng\1\0\0\1\0\0\0\0\0\0\17ip-10-10-84-118\1i\4w"..., 44}], msg_controllen=0, msg_flags=MSG_DONTROUTE|MSG_TRUNC|MSG_DONTWAIT|MSG_SYN|MSG_CONFIRM|MSG_RST|MSG_NOSIGNAL|MSG_MORE|MSG_WAITFORONE|MSG_CMSG_CLOEXEC|0x1b080010}, 44}, {{msg_name(0)=NULL, msg_iov(1)=[{"s\212\1\0\0\1\0\0\0\0\0\0\17ip-10-10-84-118\1i\4w"..., 44}], msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK|MSG_CTRUNC}, 44}}, 2, MSG_NOSIGNAL) = 2
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [100])               = 0
recvfrom(3, "ng\205\203\0\1\0\0\0\1\0\0\17ip-10-10-84-118\1i\4w"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, [16]) = 100
gettimeofday({1516398059, 60895}, NULL) = 0
poll([{fd=3, events=POLLIN}], 1, 4998)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [100])               = 0
recvfrom(3, "s\212\205\203\0\1\0\0\0\1\0\0\17ip-10-10-84-118\1i\4w"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, [16]) = 100
close(3)                                = 0
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, 16) = 0
gettimeofday({1516398059, 61143}, NULL) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendmmsg(3, {{{msg_name(0)=NULL, msg_iov(1)=[{"\366&\1\0\0\1\0\0\0\0\0\0\17ip-10-10-84-118\0\0\1\0"..., 33}], msg_controllen=0, msg_flags=MSG_DONTROUTE|MSG_TRUNC|MSG_DONTWAIT|MSG_SYN|MSG_CONFIRM|MSG_RST|MSG_NOSIGNAL|MSG_MORE|MSG_WAITFORONE|MSG_CMSG_CLOEXEC|0x1b080010}, 33}, {{msg_name(0)=NULL, msg_iov(1)=[{"\\\310\1\0\0\1\0\0\0\0\0\0\17ip-10-10-84-118\0\0\34\0"..., 33}], msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK|MSG_DONTROUTE}, 33}}, 2, MSG_NOSIGNAL) = 2
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [108])               = 0
recvfrom(3, "\\\310\201\203\0\1\0\0\0\1\0\0\17ip-10-10-84-118\0\0\34\0"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, [16]) = 108
gettimeofday({1516398059, 65488}, NULL) = 0
poll([{fd=3, events=POLLIN}], 1, 4995)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [108])               = 0
recvfrom(3, "\366&\201\203\0\1\0\0\0\1\0\0\17ip-10-10-84-118\0\0\1\0"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("10.10.3.23")}, [16]) = 108
close(3)                                = 0
write(2, "hostname: ", 10hostname: )              = 10
write(2, "Name or service not known", 25Name or service not known) = 25
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by timothysc** [comment] 2018-02-01 17:24
Is this still an issue?

**Comment by smcquay** [comment] 2018-02-01 17:38
I still can’t get it to work in our environment but I recognize that we have special settings for dns/dhcp that may be causing this.

I have switched gears and moved to creating a new vpc and am looking into vpc bridging as a way to move forward. I am fine closing this as a dupe of #118.

**Closed** 2018-02-01 17:39 UTC
Labels: p1 - Important
