### ISSUE TITLE
Kubeconfig endpoint uses ip address instead of cname

### ISSUE THREAD

**Issue by stevesloka** [heptio/aws-quickstart#235] opened 2018-12-13 20:32 UTC
**What steps did you take and what happened:**

After a cluster is built, the downloaded config uses the IP address of the ELB instead of the DNS name. This causes a problem if the IP address changes breaking the connection to the cluster.

**Comment by stevesloka** [comment] 2018-12-13 20:32
// cc @chuckha

**Comment by vincepri** [comment] 2019-01-03 00:39
During the last refresh the IP address was chosen instead of the cname because of https://github.com/heptio/aws-quickstart/blob/master/scripts/setup-k8s-master.sh.in#L127-L130

We need to investigate if this is still the case or if the address can now be a cname instead.

**Comment by johnSchnake** [comment] 2019-01-29 16:58
According to https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/initconfiguration.go#L116 it still needs to be an ipv4 or ipv6 address and not a cname.

**Comment by johnSchnake** [comment] 2019-01-30 17:52
Created an upstream issue: https://github.com/kubernetes/kubernetes/issues/73530 I think that is the right route here. I'll leave this open here in case we want to monitor the upstream change and react accordingly if it goes in. Otherwise if you think we can close (since no action can be taken now), feel free.

**Comment by johnSchnake** [comment] 2019-01-30 18:50
I found https://github.com/kubernetes/kubeadm/issues/1057 where this had been raised before for kubeadm. Going to think try and grock this a bit more as @liztio already spent some time considering this apparently.

**Comment by johnSchnake** [comment] 2019-01-30 20:59
So looking through the kubeadm code there does seem to be a discrepency between the validations that occur. I've confirmed that the `kubeadm init --config` flow does allow the cname but doesn't seem to hit the same validation logic that `kubeadm alpha kubeconfig` hits w.r.t. this value. Will look into it a bit more but in the meantime should have an easier fix for this where we can just swap out the IP for DNS name manually.

**Closed** 2019-01-31 04:14 UTC
Labels: p1 - Important
