### ISSUE TITLE
QS fails to launch when creating the master node

### ISSUE THREAD

**Issue by emcfins** [heptio/aws-quickstart#65] opened 2017-06-21 19:59 UTC
Getting the error:

14:05:11 UTC-0400 	CREATE_FAILED 	AWS::EC2::Instance 	K8sMasterInstance 	Received FAILURE signal with UniqueId i-XXXXXXXX

The EC2 itself launches but it fails when labeling the master node with the role of master.

# Label this node as a master
kubectl label node "$(hostname -f)" "kubernetes.io/role=master"

~$ hostname -f
hostname: Name or service not known

**Comment by kensimon** [comment] 2017-06-23 18:19
Hello, sorry it took a bit to respond to this.

This seems strange, as it suggests that the EC2 instance doesn't have working networking/DNS configuration by the time the `kubectl label` step is running.

We've never seen this error on our end, can you give some steps to reproduce?  Are you creating this in a new VPC or an existing one?  Or are you doing something more customized?

**Comment by emcfins** [comment] 2017-06-23 18:56
I navigate to the [Kubernetes Quick Start](https://aws.amazon.com/quickstart/architecture/heptio-kubernetes/) landing page and click on the link to Deploy on AWS in a new VPC.
Once there, I change my region to us-east-1 then continue on with the necessary parameters.
Once launched, all goes well until it runs the /tmp/setup-k8s-master.sh, when the CFN fails.

This is the error I see in the /var/log/cfn-init.log
```
# Label this node as a master
kubectl label node "$(hostname -f)" "kubernetes.io/role=master"
hostname -f
hostname: Name or service not known
error: resource name may not be empty
```
I tried using the IP address itself for the node but that didn't work either, said it was unable to find the node.
I added the line ``` kubectl get nodes ``` above the failure to see what the node and ran the script again:

``` kubectl get nodes
NAME                         STATUS     AGE       VERSION
ip-10-0-11-32.ec2.internal   NotReady   1s        v1.6.4
```

**Comment by bchav** [comment] 2017-06-23 19:19
What's your VPC configuration? Does your VPC have dns support and dns hostnames enabled? 

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html#vpc-dns-hostnames

**Comment by emcfins** [comment] 2017-06-23 19:35
Yes - the VPC has both DNS resolution and DNS hostname enabled (set to 'yes').

I changed the command to use -A and awk and it seems to have worked running /tmp/setup-k8s-master.sh
```# Label this node as a master
kubectl label node "$(hostname -A | awk -F' ' '{print $1}')" "kubernetes.io/role=master"
hostname -A | awk -F' ' '{print $1}'
node "ip-10-0-11-32.ec2.internal" labeled 
```

**Comment by kensimon** [comment] 2017-06-23 19:55
Looks like this is a problem with how machines are configured in us-east-1... they have a search path of `us-east-1.compute.internal`, but the shortname doesn't seem to be valid address under that search path.

The `hostname -A` approach will probably work fine, I'll see if there's any better way to accomplish this.

Thanks for the report!

**Comment by kensimon** [comment] 2017-06-23 20:12
I think the issue is the DHCPOptions set we deploy to the VPC. We're configuring the domain name returned by DHCP to be `${AWS::Region}.compute.internal`, but according to the docs, us-east-1 is special: if you're using AWS-provided DNS you are supposed to use `.ec2.internal` as the domain name for your DHCP servers in that region (and only that region.)  See: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html

I'm testing a change that will special-case us-east-1 and fix up the DHCP options for that region.  I think that's a better fix than working around it in the setup phase, because the real problem is that DNS is misconfigured.

**Comment by emcfins** [comment] 2017-06-23 21:38
I agree, I think your fix will be better than the hack above. Thanks for looking into this.

**Comment by kensimon** [comment] 2017-06-23 23:16
The fix is now merged into our master branch, but won't be in the production Quick Star template until probably late next week.  In the mean time if you want to run our latest master, instructions are here: https://github.com/heptio/aws-quickstart#deploying-latest-master

**Closed by kensimon** 2017-06-23 23:16 UTC
